### PR TITLE
minor file cleanup

### PR DESCRIPTION
**Pull request by richlloydmiles**
## Result

- Just some small formatting changes

@jasonklein I really want this to be awesome, trying to help out where I can.
Let me know if I can do more.

### CODE REVIEW

**Comment by benjaminbollen** [comment]
Hi @richlloydmiles !  Thanks so much, we reviewed it yesterday and looks good.  (you'll need to rebase this on jasons branch, but better later on on master directly);

Before we can merge an external contributor's work though we need to add a Contributor License Agreement to the repository as this repository is licensed under the GPLv3 family.  We'll move this up the queue and get that in place as fast as possible.  Thanks again and I will ping you when we merge your PR;

going forward we will put forward our tasks as issues on Github and discuss them on gitter.im/openstfoundation/simpletoken;  that way you can join in and help us make this an awesome codebase indeed !

ben-

**Comment by richlloydmiles** [comment]
Sound great, thanks

**Comment by benjaminbollen** [comment]
we merged the tests; can you `git rebase master` to bring your PR up to date with master? thx

**Comment by richlloydmiles** [comment]
@benjaminbollen I think I am going to close this PR and have another look at it.

**Pull request closed without merging**
